### ISSUE TITLE
Simple_form

### ISSUE THREAD

**Issue by leofrederiche** [lleonardoll/blog#2]
Pra que serve? até agora só ta dando mais trabalho rs

**Comment by jmscarpa** [comment]
Substituí o formulário padrão.

Em 26 de fevereiro de 2015 14:49, Leonardo Camp Frederiche <
notifications@github.com> escreveu:

**Comment by leofrederiche** [comment]
Ele deixo tudo meio bagunçado, como se fosse mobile. Colocar um CSS  com !important nele não é muito certo, né?

**Comment by jmscarpa** [comment]
Não. Olha a documentação dele. Tem instruções de como usá-lo junto do
bootstrap. Se usar as classes direitinhas dele fica show. ;) Olha lá na
documentação que vai te ajudar

Em 26 de fevereiro de 2015 16:06, Leonardo Camp Frederiche <
notifications@github.com> escreveu:
