### ISSUE TITLE
Post: exibir mensagens de "campo obrigatório" em Português

### ISSUE THREAD

**Issue by michelamaral** [lleonardoll/blog#5]
Página: http://localhost:3000/new-post
- Se tentar salvar sem preencher nenhum campo, exibe mensagem de erro. Isso tá certo, mas... deveria aparecer mensagem em português. Usar "locales".

**Comment by leofrederiche** [comment]
Oque seria esse "locales"?

**Comment by jmscarpa** [comment]
@lleonardoll locales são usados para fazer a internacionalização de sua aplicação. Acredito que para seu tipo de problema a utilização da gem "rails-18n" e a troca do default_locale no arquivo application.rb já deva solucionar seu problema.

Dê uma olhada na documentação da gem https://github.com/svenfuchs/rails-i18n

**Comment by leofrederiche** [comment]
Tentei colocar mais até agora não entendi, estou seguindo os passos conforme o git mais acabei chegando no seguinte erro: 
![screenshot from 2015-03-06 00 24 22](https://cloud.githubusercontent.com/assets/6271955/6519726/4234eb98-c397-11e4-8a75-69e40d841e14.png)

Não sei se é no development.rb que teria que colocar essa linha, mais ficou assim: 
![screenshot from 2015-03-06 00 24 39](https://cloud.githubusercontent.com/assets/6271955/6519747/82a6ab62-c397-11e4-9151-0b0416b82a3f.png)

Coloquei o arquivo do locale pt-BR.yml no pasta locale.

**Comment by jmscarpa** [comment]
Essa linha d development.rb é no application.rb . lembre-se sempre de
fechar o servidor e abrir novamente sempre que alterar qualquer arquivo
fora da pasta APP/

**Comment by michelamaral** [comment]
Leonardo, que nem o @jmscarpa falou, remove a linha 36 do arquivo "development.rb".
Também percebi que a linha está errada, tem um ":de" nela.

Inclui no arquivo "application.rb" isso:

```
config.i18n.default_locale = :"pt-BR"
config.time_zone = 'Brasilia'
```

**Comment by leofrederiche** [comment]
Ah Vlw, mais precisa configurar mais alguma coisa? porque as mensagens ainda estão em inglês.
