### ISSUE TITLE
Home: Remover texto irrelevante

### ISSUE THREAD

**Issue by michelamaral** [lleonardoll/blog#6]
Página: http://localhost:3000/
- Não entendi o texto "Esse é meu titulo" na página principal. Qual a função dele? Serve pra que? Lembre-se sempre que seu site ou um projeto que você esteja fazendo para um cliente, acima de tudo, é um produto e como tal deve sempre se comunicar com o usuário de forma profissional. Tanto aparência, como texto.

**Comment by leofrederiche** [comment]
Retirei o "Bem vindo" e adicionei o meu nome, como se fosse o meu blog, também mudei o texto da pagina home.
