### ISSUE TITLE
Design geral

### ISSUE THREAD

**Issue by michelamaral** [lleonardoll/blog#7]
- O layout pode ser melhorado. 
- O texto do post, pode ser formatado de forma melhor. 
  O texto está tudo "grudado", sem parágrafos, quebra de linha. Acho que é só usar "html_safe" para o campo "post.text" que resolve. Certo @jmscarpa?

**Comment by leofrederiche** [comment]
Criei um submenu lateral no estilo do blog da kaelum com os links para outros posts, e utilizei a tag "pre" para exibir as postagens, mais tive um problema, a quebra de linha também está quebrando palavras, dei uma pesquisa mais não achei nada para resolver, alguma ideia?
